apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: 171756462728.dkr.ecr.us-east-1.amazonaws.com/lab1_repo:latest
      imagePullSecrets:
        - name: ecr-registry
